### ISSUE TITLE
Cache not working correctly

### ISSUE THREAD

**Issue by yumedia** [Japnime/Google-Drive-Stream-Proxy#10]
I'm using nginx from this script https://vpssim.com/

First, script create cache file and player run normal, but after some minutes ( 10-20 minutes maybe ), the player show: Error loading media file could not be played

Then when I get that error, I tried to remove all cache file in cache folder, and player working again, and after time error return again and again..., so it waste time to do it everytime and have to check manually, please give me solution, thank you !

Also I install vpssim with PHP version 5.6.32

**Comment by Yokutto** [comment]
Upgrade your script to latest version
or set your cache file permissions to 770

**Comment by yumedia** [comment]
@Yokutto Server script and this stream code already latest version, nginx ver 1.13.7, php ver 5.6.32, and folder cache is 777, still get error mate.

**Comment by Yokutto** [comment]
@yumedia this is weird, i use the script and works normally

**Comment by japnimedev** [comment]
@yumedia I'll recheck the code if there's a compatibility problem.

**Comment by yumedia** [comment]
Please check and fix soon, you should install http://vpssim.com 's script and test !

**Comment by herogamee** [comment]
Hi my bro, I have same problem.
-------------------------------
First, script create cache file and player run normal, but after some minutes ( 10-20 minutes maybe ), the player show: Error loading media file could not be played
Then when I get that error, I tried to remove all cache file in cache folder, and player working again
-------------------------------
"Press play first" it show: Error loading media file could not be played too.

**Comment by Yokutto** [comment]
@yumedia @herogamee in `embed.php` line 12 change `$timeout = 15000;` to `$timeout = 900;` to refresh cache after pass 15 minutes

**Comment by yumedia** [comment]
@Yokutto Do you put that 900 in your script? Because I see you tell that you run normal, it you still put 15000 as script default and run normal, so I think when change to 900 the problem still happen.

**Comment by Yokutto** [comment]
@yumedia yes, i set it to 900 and i never have problem with cache

**Comment by herogamee** [comment]
@Yokutto Thank you for your advice. I will use it
And I have another question,

Does this script cause my server to hard work?
If someone visits my site about 300-500 people at the same time.

My server
CPU: 4 vCore
RAM: 8192 MB

**Comment by Yokutto** [comment]
@herogamee i use the script with 1 GB vps to 150 users online and never have any problem. but the network sometimes overload with 100 MBPS network

**Comment by aalfiann** [comment]
@herogamee i use this script with arround 400 user online at the same time. Its fine, no problem.. 

Server: 
CPU: 2 vCore
Ram: 512mb
Centos 6.4 32bit
Php server : apache + nginx reverse proxy

**Comment by herogamee** [comment]
@aalfiann @yumedia Hi bro, i use this script with wordpress at the same time. Its make bad server for my website. Do you use this script only on server ?

And I have one problem is this script not working on safari or ios system , i don’t sure it can working another mobile system.

How you fix this problem ?

Thank you if you can advice me.

Happy New Year 2018 🎇🌅🎆🌄🌆

**Comment by aalfiann** [comment]
@herogamee I put this script separated from my main web server. For ios or another browser that is not supported, I created a javascript to auto switch to embed google drive originally.

**Comment by herogamee** [comment]
@aalfiann You can share script auto switch ? 
Never mind if you can't share. It's harder to develop these things.
email : gameeland@gmail.com

I do not know about proxy players or javascript.
(I bought proxy players from developers. But now it does not work)
Now many websites use my google drive link on their website, so Google Drive are often limited.

I am looking for proxy player for a long time. This script works very well. In addition to the problem I have already told.

Thank you all

**Comment by japnimedev** [comment]
@herogamee  what proxy players you bought? Google Drive ones? and Happy New Yeaaar too ;)

**Comment by herogamee** [comment]
@japnimedev Not your script, I bought another proxy jwplayer script(now it  not working).
Thank you very much for bringing this script to share not for sale.

**Comment by japnimedev** [comment]
@herogamee can i see the old function of it? just to expand some ideas

**Comment by japnimedev** [comment]
It seems that the cache system is in good status, but I'll find some way to have an ease compatibility with regards to this cache system.

**Comment by japnimedev** [comment]
New cache system is released! Thread issue #10 is closed.
