### ISSUE TITLE
blank page?

### ISSUE THREAD

**Issue by hklcf** [Japnime/Google-Drive-Stream-Proxy#14]
example.php?id=<gdrive_id>

**Comment by hklcf** [comment]
player can display at the first time (befour cache gen) but video cant play (stream.php)

![image](https://user-images.githubusercontent.com/410302/35266182-6439d66c-005d-11e8-90a9-d559b43d4b1b.png)

content-length:0

**Comment by hklcf** [comment]
after refresh the page, the player not display and example.php?id=<gdrive_id> return blank html code

**Comment by japnimedev** [comment]
@hklcf Can I see a view source of that blank page, im just curious why it didnt work

**Comment by hklcf** [comment]
@japnimedev nothing

**Comment by japnimedev** [comment]
@hklcf really like a blank sheet? :3 oh myy can you pm your url at my email (threathgfx@gmail.com)

**Comment by d4lv** [comment]
the same here.. the source is ok but the video is not play is like blank page with jw player http://prntscr.com/i4kzr2

**Comment by d4lv** [comment]
[23-Jan-2018 16:49:08 America/New_York] PHP Notice:  Undefined variable: length in /home/zmrtgwja/public_html/api/stream.php on line 6
[23-Jan-2018 16:49:08 America/New_York] PHP Notice:  Undefined index: susci in /home/zmrtgwja/public_html/api/stream.php on line 20
[23-Jan-2018 16:49:08 America/New_York] PHP Notice:  Undefined index: cnr in /home/zmrtgwja/public_html/api/stream.php on line 29

**Comment by Yokutto** [comment]
google patched.
the links are broken right now........

**Comment by Yokutto** [comment]
fix in stream.php add "susc" string to stream new generated links

//line 26~28
$ei = $_GET['ei'];
$susc= $_GET['susc'];
$driveid = openssl_decrypt(base64_decode($_GET['driveid']), $encrypt_method, $key, 0, $iv);

//line 42
$googledrive = "".$domain."videoplayback?id=$id&itag=$itag&source=$source&requiressl=$requiressl&ttl=$ttl&mm=$mm&mn=$mn&ms=$ms&mv=$mv&pl=$pl&ei=$ei&susc=$susc&driveid=$driveid&mime=$mime&cnr=$cnr&lmt=$lmt&mt=$mt&ip=$ip&ipbits=$ipbits&susci=$susci&expire=$expire&cp=$cp&sparams=$sparams&signature=$signature&key=$key&app=$app";

@d4lv this errors are common with this script, so please ignore and wait @japnimedev update stream.php file :)

**Comment by d4lv** [comment]
same error

**Comment by japnimedev** [comment]
@d4lv @hklcf patched applied guys! 
Thank you @Yokutto :)) 👍
