### ISSUE TITLE
Can't skip or jump

### ISSUE THREAD

**Issue by Izurumn** [Japnime/Google-Drive-Stream-Proxy#15]
When I try to skip to 10 minutes from 0 minute.
It doesn't work

**Comment by hklcf** [comment]
same

**Comment by hklcf** [comment]
![image](https://user-images.githubusercontent.com/410302/35318984-d7f06d26-0118-11e8-84b2-0fd737fc542e.png)

it seem range not correct

range:bytes=0-

**Comment by japnimedev** [comment]
Patching up, `stream.php` will update later :)

**Comment by japnimedev** [comment]
Status for the `stream.php`: 70%

**Comment by japnimedev** [comment]
Okay guys ;) Long awaited update is hereee! cheers 👍

**Comment by hklcf** [comment]
can skip now but range not correct
when you jump to the end of video, it start redownload the whole video start from range bytes 0

**Comment by japnimedev** [comment]
@hklcf working on it

**Comment by japnimedev** [comment]
@hklcf done! any problems after this patch?

**Comment by hklcf** [comment]
![image](https://user-images.githubusercontent.com/410302/35775117-a6dba928-09bd-11e8-9fd2-7023ce00c457.png)

loop at range bytes 0...

**Comment by Love656** [comment]
Have you found a solution to the problem?

**Comment by aalfiann** [comment]
Maybe this will work if you make curl combine with fwrite so you can catch the buffer range. It just my opinion. :D

**Comment by hklcf** [comment]
@japnimedev have you try CURLOPT_FILE?

**Comment by japnimedev** [comment]
Closed, issue will be added for the new updates.
