### ISSUE TITLE
Blank cant play the video

### ISSUE THREAD

**Issue by HandrianD** [Japnime/Google-Drive-Stream-Proxy#16]
![image](https://user-images.githubusercontent.com/10294102/35522701-9d1e67ee-054f-11e8-86ef-ec2c86a6d723.png)

its shown like that can you help me. i was use new patched code.

**Comment by Yokutto** [comment]
Can you post full URL ?

**Comment by HandrianD** [comment]
http://player.animesearch.net/stream.php?id=188386362d462a8b&itag=18&source=webdrive&requiressl=yes&mm=30&mn=sn-a5meknsy&ms=nxu&mv=u&pl=23&ttl=transient&ei=cyJwWt6UAtGIuAWr_puwCQ&susc=dr&driveid=YVJqbS8wN3BuN1ZaYi9VcUkxdDhKUUdsZXFCUEZLcmdIb1Z2R1J2NWRDSXY2MTc3UzcvTmpGMVFNejFBVTZoQg==&api=gamerse&app=explorer&mime=video/mp4&lmt=1517149137850113&mt=1517297988&ip=192.161.169.66&ck=JgH3XOVQfvI&dom=aHR0cHM6Ly9yMS0tLXNuLWE1bWVrbnN5Lmdvb2dsZXZpZGVvLmNvbS8=&ipbits=0&expire=1517301891&cp=QVNGWURfUFhXQlhOOk1mRDJCVFNOZ3NM&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ttl,ei,susc,driveid,app,mime,lmt,cp&signature=118D4EEDDE0BE1E3E5A97054CF8303A649128C80.A2AAA21A2108F9D76887479684743804031F8600&key=ck2&apps=japnimedev.net

**Comment by japnimedev** [comment]
@HandrianD is this problem still occurs?

**Comment by Jujudo** [comment]
Does not work for me :(

**Comment by japnimedev** [comment]
@TheHatMan98 Hmmmm I want to access your cpanel to check if there's a problem.

**Comment by japnimedev** [comment]
What issues left guys? :3 I have lots of free time tomorrow to recheck everything if there's something wrong

**Comment by japnimedev** [comment]
Closed due to no feedback.
