### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by iPingOi** [Japnime/Google-Drive-Stream-Proxy#19]
/stream.php?id=0B4jPFiPe7gVIVUtNRGVVWmd1Slk ??

![screenshot_11](https://user-images.githubusercontent.com/33385746/39810129-449a3f5e-535a-11e8-9d36-22de630adc91.png)

**Comment by japnimedev** [comment]
This script is dead for a while, I don't have yet time to configure things out for this issues of this script.

**Comment by iPingOi** [comment]
Okey, thx bro
