### ISSUE TITLE
Can you help me how to make direct download for each quality ?

### ISSUE THREAD

**Issue by HandrianD** [Japnime/Google-Drive-Stream-Proxy#3]
pls help me i cant do it get the data url from $gdata .
it always play video on new tab can you help me make direct it to download the video. it will great no more limited file . ty

**Comment by HandrianD** [comment]
i use like this can you resolve it , it always sow Invalid argument supplied for foreach()

<?php  
    error_reporting(0);
    include "func.php";
    
    if($_GET['id'] != ""){
        $driveid = $_GET['id'];
        $gdata = driveproxy($driveid);
    }
$data = json_decode($gdata);
    
foreach($data as $anu){
echo '<a href="'.$anu->file.'">'.$anu->label.'</a><br>'; 

}
?>

**Comment by japnimedev** [comment]
@HandrianD,
from the line:
```php
foreach ($o as $quality => $file) {
     $sources .= '{"type": "video/mp4", "label": "'.$quality.'", "file": "'.$file.'&apps=japnimeserver.com"},';
}
```
You can change the $sources that make them look like a direct download. For example:
`$sources .= '<a href="'.$file.'&apps=japnimeserver.com" target="blank">File Quality: '.$quality.'</a>;`

But I'm warning you that when they will download this files, the bandwidth of your server will be used and it may cause some "minimal" problems, I think.

**Comment by japnimedev** [comment]
You can use some like bootstrap template for good framework design.

**Comment by HandrianD** [comment]
Very nice ty
