### ISSUE TITLE
CNR String in the URL

### ISSUE THREAD

**Issue by Yokutto** [Japnime/Google-Drive-Stream-Proxy#4]
Hi!
I recently had problems with some URLs containing a "CNR". Videos that contained this in the URL were not played

Link generated: `https://streamingserverblablabal.com/?id=bbbc22572e701b6e&itag=22&source=picasa&requiressl=yes&mm=30&mn=sn-ab5szne7&ms=nxu&mv=m&pl=48&ttl=transient&ei=eLobWpeoO5bsqAW7nKbQCw&driveid=UFNOUFNSblFtY2Q1SXV2NDJyd1p2Uk13UnYxMVB3UTVMeWFsbUVVdjRXQ1hSS2lIMUx2VFdXR20xOTRuc1p1UA==&api=animesync.tv&app=explorer&mime=video/mp4&cnr=14&lmt=1511587053053883&mt=1511766564&ip=2604:a880:800:10::3a39:1&ck=rPpUKwBNF4s&dom=aHR0cHM6Ly9yNS0tLXNuLWFiNXN6bmU3Lmdvb2dsZXZpZGVvLmNvbS8=&ipbits=0&expire=1511770248&cp=QVNGU0hfT1JSSVhOOm9Tc1FJd0ZLRzNw&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ttl,ei,driveid,app,mime,cnr,lmt,cp&signature=522FDAFA52B8CB1CD10981D4B1BF29805AC3DB1E.8526E969DC925296CBF63416D1219E1FB606B03D&key=ck2&apps=animesync.tv`

Just CTRL + F and search by "cnr" in the link
This happens only in 720p quality.

The file was uploaded in google photos and passed to google drive, but the file has a link just like all other googl drive files...

Video link in google drive: https://drive.google.com/file/d/1of9OL9ymU-s-sTF2PepOk0Jsodht_yqRAw/view

Best.

**Comment by japnimedev** [comment]
@Yokutto script updated :) you can close this if the problem is solved.
Here's the updated file: https://github.com/japnimedev/Google-Drive-Stream-Proxy/blob/master/stream.php

**Comment by Yokutto** [comment]
Thats fixed.

Another question, is it possible to list the qualities from highest to lowest? eg 1080p > 720p etc...

**Comment by japnimedev** [comment]
@Yokutto go to `func.php`, find line number 92 then you will see `asort($o);`
Change that into `ksort($o);` so that the arrangement will start with 1080p

**Comment by Yokutto** [comment]
Worked, thanks for all.

**Comment by yumedia** [comment]
ip=2604:a880:800:10::3a39:1

How you can make this ip to your link, mine always show IPV4 :(

**Comment by Yokutto** [comment]
@yumedia My VPS have a ipv6 connection, and the CURL connect with ipv6. I have changed my vps so this IP 2604:a880:800:10::3a39:1 doesn't work anymore

**Comment by yumedia** [comment]
@Yokutto Where do you rent your VPS have IPV6 mate? Thank you so much !

**Comment by Yokutto** [comment]
@yumedia i use digitalocean, you can buy it via https://m.do.co/c/f9c897f0adca to gain 10 USD

**Comment by yumedia** [comment]
@Yokutto which location and which type of server ( like 5$, 10$, 20$ ) do you choose mate?

**Comment by Yokutto** [comment]
@yumedia i use NYC3 $5
every plan on every region has the same price and have ipv6 for free

**Comment by yumedia** [comment]
@Yokutto thank you so much mate !

**Comment by yumedia** [comment]
@Yokutto Which PHP version are you using, do you install any script like LAMP, LEMP? You use apache or nginx mate ?

**Comment by Yokutto** [comment]
@yumedia i use nginx 1.12 with php-fcgi 7.0. you can choose LAMP install to have the same version but with apache. That does not make much difference, your script will run fine with php 5.6+ and curl
