### ISSUE TITLE
are this player have a limit?

### ISSUE THREAD

**Issue by HandrianD** [Japnime/Google-Drive-Stream-Proxy#5]
this player cant play when video out of playing or downloading on google drive ?. 
playing from this embed can make file get limit??
oh 1 question left
how to make this work fro full url like this
https://drive.google.com/file/d/1NfI49gxmBFYMjJ2N7-pGvg1UHJ12v9Su/view

ty.

**Comment by japnimedev** [comment]
@HandrianD nope, there's no limit when using this script.
This link `https://drive.google.com/file/d/1NfI49gxmBFYMjJ2N7-pGvg1UHJ12v9Su/view` is compatible with this script so you can basically insert this id `1NfI49gxmBFYMjJ2N7-pGvg1UHJ12v9Su`.

**Comment by japnimedev** [comment]
@HandrianD you can close this issue if you don't have any questions
