### ISSUE TITLE
It doesn't work, can you help me?

### ISSUE THREAD

**Issue by Izurumn** [Japnime/Google-Drive-Stream-Proxy#6]
My stream proxy link: http://buhkino.ml/embed.php?id=13uxUht2Wq2DgM1O2Zzkq2W10A42H64rf

**Comment by japnimedev** [comment]
Can I see your error logs, if there's no error logs then please disable `error_reporting(0);` at embed.php.
I guess or probably, the hosting that you hold doesn't agree with the php functions since it's working.
![untitled](https://user-images.githubusercontent.com/29234610/33717514-2b4dd9c6-db95-11e7-93f7-52e3c9eb7cb4.png)

**Comment by Izurumn** [comment]
[07-Dec-2017 08:52:14 America/Chicago] PHP Warning:  curl_setopt() expects parameter 2 to be long, string given in /home2/izuru/buhkino.ml/stream.php on line 161
[07-Dec-2017 08:52:15 America/Chicago] PHP Warning:  curl_setopt() expects parameter 2 to be long, string given in /home2/izuru/buhkino.ml/stream.php on line 161

**Comment by japnimedev** [comment]
the error logs description are fine, yet something's wrong with the script's date system.
Go to func.php and try adding this line `date_default_timezone_set('your timezone');`, you can check here for your [default timezone](http://www.php.net/manual/en/timezones.php).
By then, delete the cache file in the cache folder and try again. If it cant go on, there's something wrong with your hosting which is Hostgator right?

**Comment by Izurumn** [comment]
Yes, my host is Hostgator. I added date_default_timezone_set but it doesn't work. What host will work this script? I think even my xampp doesn't work...

**Comment by Izurumn** [comment]
PHP Warning:  curl_setopt() expects parameter 2 to be long, string given in /home2/izuru/buhkino.ml/stream.php on line 161

It's the error, i think.

**Comment by japnimedev** [comment]
@Izurumn that error line is normal since the string given (the link) is too long. I'm using some other hosting such as Ultra Webhosting. The hostgator will be the main problem, try it from free hosting and it will work.

**Comment by Izurumn** [comment]
Thanks, hostgator was the problem.
