### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by Yokutto** [Japnime/Google-Drive-Stream-Proxy#7]
When the script asks for a URL it generates a .cache file with the response. The cache file is created and served perfectly, however, after 20 minutes the link breaks and instead of the script rewriting the response it continues serving the cache permanently. How to fix that?

**Comment by japnimedev** [comment]
@Yokutto in func.php, find the line 108 where you will locate this function `if ($timeout >= 900) {`
The variable `900` serves to be 900s equivalent to 15 minutes which means after 900 seconds, the link will change with the new fresh generated link. Probably to fix it is to change the variable approximately 30 minutes or I think more than for the viewers. Yet I kinda guess anime episodes exceed for about 24 minutes so you can test between `1500` above ;)

**Comment by Yokutto** [comment]
Even if I put the script to generate a new link every 2 seconds, it will not generate unless I go to the .cache file and delete it

**Comment by japnimedev** [comment]
@Yokutto, the .cache file doesn't change? recheck again since I've tested it and it changes tho.
You recheck with this lines from `19 - 36` and `100 - 124` in func.php

**Comment by Yokutto** [comment]
In line 19/36 the script generate a 1/1/1970 date with correct hour. When the minutes are less than the current time, the script resets the link. But when the minutes are bigger than the current date the script simply continues serving the cache file.
I tried in some ways to edit the code but it did not work. The original source cache system (https://github.com/p4v800m/Google-Drive-proxy-script-stream-jwplayer) works perfectly

![image](https://user-images.githubusercontent.com/16729837/33792171-dd63600a-dc7f-11e7-9c36-26d9ce2d5b1e.png)

**Comment by japnimedev** [comment]
@Yokutto hmm i'll recode the cache again.

**Comment by japnimedev** [comment]
@Yokutto script updated ;)

**Comment by Yokutto** [comment]
It's working now, thanks, your help is very appreciated.
