### ISSUE TITLE
Video can't not play on safari MacOS

### ISSUE THREAD

**Issue by anhnvme** [Japnime/Google-Drive-Stream-Proxy#8]
Hello,

Do u know why video can't play on Safari in Mac and iPhone ?
Chrome, Firefox is ok

**Comment by japnimedev** [comment]
@anhnvme the player itself doesn't play or the proxy urls?

**Comment by anhnvme** [comment]
I'm upload source to hosting then running it. So i think is proxy URL :D

**Comment by japnimedev** [comment]
@anhnvme I'll be further investigating that problem

**Comment by anhnvme** [comment]
Let me know if you need more information.
Thanks you so much

**Comment by aalfiann** [comment]
@anhnvme On IOS, the header Accept-Ranges: bytes should be define with start and end length.
This should fix the problem, unfortunately I don't have that device so I can't make a test.

Example: 
```
header('Accept-Ranges: bytes 0-'.$size2);
```

Just edit the file stream.php at line 121 and 124, then let us know if this will fix or not.

For further information, maybe this link will helps >> https://mobiforge.com/design-development/content-delivery-mobile-devices

**Comment by anhnvme** [comment]
@aalfiann thanks you, i'm tried but not working :( 
Can you put code on here ?

**Comment by anhnvme** [comment]
@japnimedev i see this code can play at mobile and mac but it not showing low quality link
https://github.com/ArdiArtani/Google-Drive-Player-Script
You can look into it

Thanks you so much

**Comment by Yokutto** [comment]
this problem also occurs on PS4 browser

**Comment by japnimedev** [comment]
Got a question, the links executed to white screen or black screen with the player?

**Comment by anhnvme** [comment]
black screen guy

**Comment by japnimedev** [comment]
@anhnvme with the player or just black screen?

**Comment by anhnvme** [comment]
@japnimedev yes, it's black screen only, but while i'm using developer tool, i see video still download, just not play

**Comment by japnimedev** [comment]
@anhnvme just a wild guess, is useragent may affect from this kind of problem?

**Comment by anhnvme** [comment]
Hello,

No, because i'm play on Safari on MacOS still not working, Chrome, Firefox working fine

**Comment by japnimedev** [comment]
I'm trying to process this problem, I'll do my best to patch this up asap ;) (well studies first before this).
