### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by yumedia** [Japnime/Google-Drive-Stream-Proxy#9]
Working

**Comment by japnimedev** [comment]
@yumedia I dont really have the idea yet try this method that I've been thinking out.
So first open your cmd then type `nslookup website.com` replace website.com to what site you want to lookup.
Then you will see:
```
Server:  UnKnown
Address:  xxxx::xxxx::xxxx::xxxxx
```
By that, get the mac address, then go to `func.php` and find the line 69 and replace `&ip=$1&` with the mac address you got like `&ip=xxxx::xxxx::xxxx::xxxx::&`

Feedbacks if it works, but I'm probably finding the solution in an automatically yet try this method.

**Comment by yumedia** [comment]
I use linux, command: ifconfig -a and found out: ether 00:xx:xx:xx:xx:xx and replace line 69 as you said but it not working mate
